Network.delete_all
freeman = Network.create("network" => "Freeman Fambly")
smith = Network.create("network" => "Smith Family")
davidson = Network.create("network" => "Davidson Family")
jiwani = Network.create("network" => "Jiwani Family")

User.delete_all
kat = User.create("username" => "kfreestyle", "password" => "freeman", "name" => "Kathryn Freeman", "email_address" => "kathryn.m.freeman@gmail.com", "member_since" => "May 2014", "tagline" => "More avocado, please.", "network_id" => freeman["id"])
elisa = User.create("username" => "elisavanoss", "password" => "smith", "name" => "Elisa Smith", "email_address" => "elisa_vanoss@yahoo.com", "member_since" => "May 2014", "tagline" => "To be completed.", "network_id" => freeman["id"])
christie = User.create("username" => "christinad", "password" => "davidson", "name" => "Christina Davidson", "email_address" => "christina.freeman@gmail.com", "member_since" => "May 2014", "tagline" => "To be completed.", "network_id" => freeman["id"])
mike = User.create("username" => "mjiwani", "password" => "jiwani", "name" => "Michael Jiwani", "email_address" => "mike.jiwani@gmail.com", "member_since" => "May 2014", "tagline" => "To be completed.", "network_id" => jiwani["id"])
User.create("username" => "AdeleDazeem", "password" => "letitgo", "name" => "Idina Menzel", "email_address" => "frozen@gmail.com", "member_since" => "June 2014", "tagline" => "Do you want to build a snowman?", "network_id" => davidson["id"])

Recipe.delete_all
squash = Recipe.create("recipe_name" => "Squash on Toast", "recipe_URL" => "http://www.nytimes.com/recipes/12944/jean-georges-vongerichtens-squash-on-toast.html", "recipe_photo" => "http://graphics8.nytimes.com/images/2012/11/14/dining/14BITTMAN_SPAN/14BITTMAN-popup.jpg", "recipe_added" => "May 28, 2014", "star_rating" => "5", "notes" => "Perfect as-is.  From the NYTimes.", "user_id" => kat["id"], "category_name" => "Appetizer")
Recipe.create("recipe_name" => "Lemon Garlic Shrimp with Veggies", "recipe_URL" => "http://www.eatingwell.com/recipes/lemon_garlic_shrimp_vegetables.html", "recipe_photo" => "http://bed56888308e93972c04-0dfc23b7b97881dee012a129d9518bae.r34.cf1.rackcdn.com/sites/default/files/imagecache/standard/recipes/MF6435.JPG", "recipe_added" => "April 8, 2014", "star_rating" => "4", "notes" => "Easy and delicious!", "user_id" => christie["id"], "category_name" => "Main Dish")
scones = Recipe.create("recipe_name" => "Chocolate Chip Breakfast Scones", "recipe_URL" => "http://sugarywinzy.com/chocolate-chip-breakfast-scones/", "recipe_photo" => "http://sugarywinzy.com/wp-content/uploads/2013/04/SugaryWinzy-Chocolate-Chip-Breakfast-Scones2.jpg", "recipe_added" => "December 27, 2013", "star_rating" => "4", "notes" => "Fun and easy to make!  Don't skip the egg wash, and I recommend dusting them with sugar after brushing them with egg.", "user_id" => kat["id"], "category_name" => "Breakfast")
gnocci = Recipe.create("recipe_name" => "Skillet Gnocchi with Chard and White Beans", "recipe_URL" => "http://www.eatingwell.com/recipes/skillet_gnocchi_with_chard_white_beans.html", "recipe_photo" => "http://bed56888308e93972c04-0dfc23b7b97881dee012a129d9518bae.r34.cf1.rackcdn.com/sites/default/files/imagecache/standard/recipes/MV6769.JPG", "recipe_added" => "January 22, 2013", "star_rating" => "4", "notes" => "I used extra cheese, but that's just me.", "user_id" => kat["id"], "category_name" => "Main Dish")
Recipe.create("recipe_name" => "Alton Brown's Guacamole", "recipe_URL" => "http://www.foodnetwork.com/recipes/alton-brown/guacamole-recipe.html", "recipe_photo" => "http://foodnetwork.sndimg.com/content/dam/images/food/fullset/2011/4/7/0/EA1F08_guacamole_s4x3.jpg.rend.sni12col.landscape.jpeg", "recipe_added" => "January 22, 2013", "star_rating" => "5", "notes" => "Killer guac.  Don't skimp on the lime juice.", "user_id" => kat["id"], "category_name" => "Appetizer")
Recipe.create("recipe_name" => "Perfect Pancakes", "recipe_URL" => "http://www.bigoven.com/recipe/pefect-pancake-batter/3629", "recipe_photo" => "http://mda.bigoven.com/pics/rs/256/pefect-pancake-batter.jpg", "recipe_added" => "June 2014", "star_rating" => "5", "notes" => "After mixing all of the ingredients, let the batter stand! Then don't mix again before cooking. It really does make a difference.", "user_id" => kat["id"], "category_name" => "Breakfast")
Recipe.create("recipe_name" => "Easy Paella", "recipe_URL" => "http://allrecipes.com/recipe/easy-paella/", "recipe_photo" => "http://images.media-allrecipes.com/userphotos/250x250/00/88/64/886465.jpg", "recipe_added" => "June 2014", "star_rating" => "3", "notes" => "Monitor closely -- be careful not to dry it out.", "user_id" => mike["id"], "category_name" => "Main Dish")
Recipe.create("recipe_name" => "Easy Mexican Dip", "recipe_URL" => "http://allrecipes.com/recipe/chili-cheese-dip-iii/", "recipe_photo" => "http://images.media-allrecipes.com/userphotos/250x250/00/24/20/242067.jpg", "recipe_added" => "June 2014", "star_rating" => "4", "notes" => "Can't go wrong -- so easy and addicting!", "user_id" => kat["id"], "category_name" => "Appetizer")
Recipe.create("recipe_name" => "Mexican Stuffed Shells", "recipe_URL" => "http://www.bigoven.com/recipe/mexican-stuffed-shells/281421", "recipe_photo" => "", "recipe_added" => "June 2014", "star_rating" => "4", "notes" => "This is insane. Definitely not health food. But so yummy.", "user_id" => mike["id"], "category_name" => "Main Dish")
Recipe.create("recipe_name" => "Beet Tzaziki", "recipe_URL" => "http://www.nytimes.com/2010/04/28/health/nutrition/28recipehealth.html?_r=0", "recipe_photo" => "http://graphics8.nytimes.com/images/2010/04/27/science/28recipehealth_600/28recipehealth_600-articleLarge.jpg", "recipe_added" => "June 2014", "star_rating" => "4", "notes" => "So simple.  Roast the beets with their skin on in foil pouches with a little Olive Oil and the skins will rub right off.", "user_id" => kat["id"], "category_name" => "Appetizer")

Comment.delete_all
Comment.create("recipe_id" => squash["id"], "comment" => "So delicious! A little tricky to make.")
Comment.create("recipe_id" => squash["id"], "comment" => "Be careful not to burn the onions while you're carmelizing them -- takes a good amount of attention!")
Comment.create("recipe_id" => squash["id"], "comment" => "Worth the effort.")
Comment.create("recipe_id" => scones["id"], "comment" => "So fun to make!")
Comment.create("recipe_id" => scones["id"], "comment" => "An easy project to make with kids.")
Comment.create("recipe_id" => scones["id"], "comment" => "The dough is fun to play with -- and the result is fabulous!")
Comment.create("recipe_id" => scones["id"], "comment" => "Be careful not to overcook these guys.")
Comment.create("recipe_id" => gnocci["id"], "comment" => "Not as good without the extra cheese.")
